name: flutter_native_timezone
description: A flutter plugin for getting the local timezone of the device.
version: 2.0.2
homepage: https://github.com/pinkfish/flutter_native_timezone

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.flutter_native_timezone
        pluginClass: FlutterNativeTimezonePlugin
      ios:
        pluginClass: FlutterNativeTimezonePlugin
      macos:
        pluginClass: FlutterNativeTimezonePlugin
      web:
        pluginClass: FlutterNativeTimezonePlugin
        fileName: flutter_native_timezone_web.dart
